# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69e4a58c9927fd015d04d60baa92c7c3b0ce797d907ef7dda2c609d1dc3e2fd418da384172444622b19f85acb619f33ac0ee77eba323ae7a91ddaa3031047bf3

test:
  secret_key_base: 509facb9baf5170e720d53282164b630d0c1fc3cd23cfeda1caab7397a3fa1a8f0d8e00b7852a9a1d9c397c3b85bccdf673b0ab764b70608b0f04e8c76ac54f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
